changelog:
   categories:
    - title: Features
       labels:
         - RN: MAJOR FEATURE
         - RN: MINOR FEATURE
    - title: Fixes
       labels:
         - RN: BUGFIX
         - RN: SAFETY IMPROVEMENT
         - RN: IMPROVEMENT
    - title: Targets
       labels:
         - RN: NEW TARGET
         - RN: TARGET UPDATE
    - title: Known Issues
       labels: 
         - BUG
